// <auto-generated />
using System;
using LearningPlatform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningPlatform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningPlatform.Models.Cart", b =>
            {
                b.Property<int>("CartId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(
                    b.Property<int>("CartId"));

                b.Property<decimal>("Amount")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int?>("MasterCourseId")
                    .HasColumnType("int");

                b.Property<int?>("SubCourseId")
                    .HasColumnType("int");

                b.Property<int?>("SubscriptionId")
                    .HasColumnType("int");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("CartId");

                b.HasIndex("MasterCourseId");

                b.HasIndex("SubCourseId");

                b.HasIndex("SubscriptionId");

                b.HasIndex("UserId");

                b.ToTable("Cart");
            });

            modelBuilder.Entity("LearningPlatform.Models.MasterCourse", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(
                    b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("MasterCourseName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Thumbnail")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("MasterCourse");
            });

            modelBuilder.Entity("LearningPlatform.Models.SubCourse", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(
                    b.Property<int>("Id"));

                b.Property<decimal>("Amount")
                    .HasColumnType("decimal(10,2)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("MasterCourseId")
                    .HasColumnType("int");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("SubCourseName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Thumbnail")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("MasterCourseId");

                b.ToTable("SubCourse");
            });

            modelBuilder.Entity("LearningPlatform.Models.Subscription", b =>
            {
                b.Property<int>("sid")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(
                    b.Property<int>("sid"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("CreatedBy")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("MasterCourseId")
                    .HasColumnType("int");

                b.Property<int>("SubCourseId")
                    .HasColumnType("int");

                b.Property<string>("Thumbnail")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Validity")
                    .HasColumnType("int");

                b.Property<int>("amount")
                    .HasColumnType("int");

                b.Property<string>("status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("stype")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("sid");

                b.HasIndex("MasterCourseId");

                b.HasIndex("SubCourseId");

                b.ToTable("Subscription");
            });

            modelBuilder.Entity("LearningPlatform.Models.User", b =>
            {
                b.Property<int>("UserId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(
                    b.Property<int>("UserId"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("UserId");

                b.ToTable("User");
            });

            modelBuilder.Entity("LearningPlatform.Models.Cart", b =>
            {
                b.HasOne("LearningPlatform.Models.MasterCourse", "MasterCourseData")
                    .WithMany()
                    .HasForeignKey("MasterCourseId");

                b.HasOne("LearningPlatform.Models.SubCourse", "SubCourseData")
                    .WithMany()
                    .HasForeignKey("SubCourseId");

                b.HasOne("LearningPlatform.Models.Subscription", "SubscriptionData")
                    .WithMany()
                    .HasForeignKey("SubscriptionId");

                b.HasOne("LearningPlatform.Models.User", "UserData")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("MasterCourseData");

                b.Navigation("SubCourseData");

                b.Navigation("SubscriptionData");

                b.Navigation("UserData");
            });

            modelBuilder.Entity("LearningPlatform.Models.SubCourse", b =>
            {
                b.HasOne("LearningPlatform.Models.MasterCourse", "MasterCourse")
                    .WithMany()
                    .HasForeignKey("MasterCourseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("MasterCourse");
            });

            modelBuilder.Entity("LearningPlatform.Models.Subscription", b =>
            {
                b.HasOne("LearningPlatform.Models.MasterCourse", "MasterCourseData")
                    .WithMany()
                    .HasForeignKey("MasterCourseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("LearningPlatform.Models.SubCourse", "SubCourseData")
                    .WithMany()
                    .HasForeignKey("SubCourseId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.Navigation("MasterCourseData");

                b.Navigation("SubCourseData");
            });

#pragma warning restore 612, 618
        }
    }
}